$(document).ready(function(){
    $(".button").click(function(){
      $("#div1").hide();
    });
    $(".button2").click(function(){
        $("#div2").hide();
      });
      $(".button3").click(function(){
        $("#div3").hide();
      });
  });